# daemon runs in the background
# run something like tail /var/log/chainturkd/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/chainturkd:/var/lib/chainturkd -v $(pwd)/wallet:/home/chainturk --rm -ti chainturk:latest
FROM ubuntu:16.04

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

ADD https://github.com/just-containers/socklog-overlay/releases/download/v2.1.0-0/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

COPY . /src/chainturk


# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost1.58-all-dev && \
    cd /src/chainturk && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) && \
    mkdir -p /usr/local/bin && \
    cp src/ChainTurkd /usr/local/bin/ChainTurkd && \
    cp src/walletd /usr/local/bin/walletd && \
    cp src/zedwallet /usr/local/bin/zedwallet && \
    cp src/miner /usr/local/bin/miner && \
    strip /usr/local/bin/ChainTurkd && \
    strip /usr/local/bin/walletd && \
    strip /usr/local/bin/zedwallet && \
    strip /usr/local/bin/miner && \
    cd / && \
    rm -rf /src/chainturk && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55

# setup the chainturkd service
RUN useradd -r -s /usr/sbin/nologin -m -d /var/lib/chainturkd chainturkd && \
    useradd -s /bin/bash -m -d /home/chainturk chainturk && \
    mkdir -p /etc/services.d/chainturkd/log && \
    mkdir -p /var/log/chainturkd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/chainturkd/run && \
    echo "fdmove -c 2 1" >> /etc/services.d/chainturkd/run && \
    echo "cd /var/lib/chainturkd" >> /etc/services.d/chainturkd/run && \
    echo "export HOME /var/lib/chainturkd" >> /etc/services.d/chainturkd/run && \
    echo "s6-setuidgid chainturkd /usr/local/bin/ChainTurkd" >> /etc/services.d/chainturkd/run && \
    chmod +x /etc/services.d/chainturkd/run && \
    chown nobody:nogroup /var/log/chainturkd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/chainturkd/log/run && \
    echo "s6-setuidgid nobody" >> /etc/services.d/chainturkd/log/run && \
    echo "s6-log -bp -- n20 s1000000 /var/log/chainturkd" >> /etc/services.d/chainturkd/log/run && \
    chmod +x /etc/services.d/chainturkd/log/run && \
    echo "/var/lib/chainturkd true chainturkd 0644 0755" > /etc/fix-attrs.d/chainturkd-home && \
    echo "/home/chainturk true chainturk 0644 0755" > /etc/fix-attrs.d/chainturk-home && \
    echo "/var/log/chainturkd true nobody 0644 0755" > /etc/fix-attrs.d/chainturkd-logs

VOLUME ["/var/lib/chainturkd", "/home/chainturk","/var/log/chainturkd"]

ENTRYPOINT ["/init"]
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv cd /home/chainturk export HOME /home/chainturk s6-setuidgid chainturk /bin/bash"]
