version: '3'

services:
  node1:
    image: funkypenguin/chainturk
    container_name: chainturktest-node1
    volumes:
      - ../chainturkd:/var/lib/chainturkd/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/chainturk
#    container_name: chainturktest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/chainturk
#    container_name: chainturktest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

